title = "Corridor Toronto-Ottawa"
heading = "Toronto-Ottawa services"
aria_label = "Toronto Ottawa"
reference_date = "20240606"
# This timetable gets split programmatically
max_columns_per_page = 11
landscape = true
key_r = true
key_d = true
wheelchair_advance_notice = true
montreal_airport_shuttle = true
for_rpa = false
