title = "Borealis (Twin Cities-Milwaukee-Chicago) Timetable"
heading = "Borealis (Twin Cities-Milwaukee-Chicago)"
aria_label = "Borealis (Twin Cities-Milwaukee-Chicago)"
reference_date = "20240521"
train_numbers_side_by_side = true
key_on_right = false
key_baggage = true
key_d = true
key_r = true
key_tz = true
for_rpa = true
