title = "Capitol Corridor Weekday Westbound"
heading = "Capitol Corridor: Weekday Westbound"
aria_label = "Capitol Corridor Weekday Westbound"
landscape = true
reference_date = "20240102"
bottom_text = "Trains <b>may leave 5 minutes early</b> at Santa Clara/Great America and Santa Clara Transit Center"
key_bus = true
use_bus_icon_in_cells = true
key_baggage = true
key_r = true
for_rpa = true
