title = "Capitol Corridor Weekend Westbound"
heading = "Capitol Corridor: Weekend Westbound"
aria_label = "Capitol Corridor Weekend Westbound"
programmers_warning = "Not revised because of ghost buses and real buses which aren't in GTFS."
landscape = true
reference_date = "20240601"
bottom_text = "Trains <b>may leave 5 minutes early</b> at Santa Clara/Great America and Santa Clara Transit Center"
compress_credits = true
key_bus = true
use_bus_icon_in_cells = true
key_baggage = true
key_d = true
for_rpa = true
