title = "Carolinian and Piedmont Northbound"
heading = "Carolinian and Piedmont Northbound"
aria_label = "Carolinian Piedmont Northbound"
reference_date = "20240505"
programmers_warning = "Train 80, 19, and 20 have weird variations on incoming NEC timings."
key_baggage = true
key_d = true
for_rpa = true
