title = "Empire Service Weekend Eastbound"
heading = "Empire Service: Weekend Eastbound & Southbound"
aria_label = "Empire Service Weekend Eastbound"
top_text = "NOTE: Empire Service corridor work during summer 2024. Please see <b><a href=\"https://www.amtrak.com/service-alerts-and-notices\">https://www.amtrak.com/service-alerts-and-notices</a></b> for the latest schedule adjustments."
landscape = true
reference_date = "20240620"
key_baggage = true
key_d = true
all_stations_accessible = true
for_rpa = true
