title = "Hiawatha Southbound"
heading = "Hiawatha: Southbound"
aria_label = "Hiawatha Southbound"
reference_date = "20240620"
top_text = "Check <a href=\"https://amtrakhiawatha.com\">AmtrakHiawatha.com</a> for additional and connecting bus service and updated schedules."
key_baggage = true
for_rpa = true
transposed = true
