title = "Charlottesville, Lynchburg, & Roanoke Timetable - Southbound"
heading = "Charlottesville, Lynchburg, & Roanoke - Southbound"
agency_css_class = "amtrak-to-css"
aria_label = "Roanoke Southbound"
reference_date = "20240620"
key_baggage = true
key_d = true
key_r = true
for_rpa = true
