title = "Charlottesville, Lynchburg, & Roanoke Timetable - Northbound"
heading = "Charlottesville, Lynchburg, & Roanoke - Northbound"
agency_css_class = "amtrak-to-css"
aria_label = "Roanoke Northbound"
reference_date = "20240620"
key_baggage = true
key_d = true
key_r = true
for_rpa = true
