title = "Amtrak's Northeast Corridor: Sunday Southbound"
heading = "Northeast Corridor: Sunday Southbound"
aria_label = "Northeast Corridor Sunday Southbound"
reference_date = "20240205"
# This timetable gets split programmatically
# Problem trains to double-check: 20, 80, 98
max_columns_per_page = 9
landscape = true
key_on_right = true
key_baggage = true
key_d = true
key_r = true
for_rpa = true

