title = "Amtrak's Northeast Corridor: Saturday Northbound"
heading = "Northeast Corridor: Saturday Northbound"
aria_label = "Northeast Corridor Saturday Northbound"
reference_date = "20240620"
# This timetable gets split programmatically
# Problem trains to double-check: 19, 79, 97
max_columns_per_page = 9
landscape = true
key_on_right = true
key_baggage = true
key_d = true
key_r = true
for_rpa = true
