title = "Pacific Surfliner Southbound"
heading = "Pacific Surliner: Southbound"
aria_label = "Pacific Surfliner Southbound"
landscape = true
reference_date = "20240620"
key_baggage = true
key_d = true
for_rpa = true
