title = "Richmond & Hampton Roads Timetable - Sunday Northbound"
heading = "Richmond & Hampton Roads - Sunday Northbound"
amtrak_css_class = "amtrak-to-css"
aria_label = "Richmond Sunday Northbound"
reference_date = "20240608"
key_baggage = true
key_d = true
compress_credits = true
for_rpa = true
