title = "Richmond & Hampton Roads Timetable - Weekday Southbound"
heading = "Richmond & Hampton Roads - Weekday Southbound"
amtrak_css_class = "amtrak-to-css"
aria_label = "Richmond Weekday Southbound"
reference_date = "20240124"
key_baggage = true
key_r = true
compress_credits = true
for_rpa = true
