title = "Richmond & Hampton Roads Timetable - Saturday Northbound"
heading = "Richmond & Hampton Roads - Saturday Northbound"
amtrak_css_class = "amtrak-to-css"
aria_label = "Richmond Saturday Northbound"
reference_date = "20240601"
key_baggage = true
key_d = true
compress_credits = true
for_rpa = true
