title = "San Joaquins Northbound"
heading = "San Joaquins: Northbound"
aria_label = "San Joaquins Northbound"
landscape = true
reference_date = "20240620"
key_baggage = true
key_r = true
key_d = true
key_l = true
for_rpa = true
