title = "Southwest Chief Timetable"
heading = "Southwest Chief"
aria_label = "Southwest Chief"
reference_date = "20231230"
key_on_right = true
key_baggage = true
key_d = true
key_r = true
key_tz = true
mountain_standard_time = true
for_rpa = true
