title = "Vermont to Upstate NY Timetable"
heading = "Vermont to Upstate NY & points west"
agency_css_class = "amtrak-colon-css"
aria_label = "Vermont to Upstate New York"
reference_date = "20240620"
train_numbers_side_by_side = true
compress_credits = true
for_rpa = true
